name: CD

on:
  push:
    branches:
      - "dev/*"

env:
  NODE_VERSION: "18.13"
  NPM_REGISTRY_URL: "https://npm.pkg.github.com/"

jobs:
  push_version_commit:
    if: "!contains(github.event.head_commit.message, 'ver: ')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Regist author
        run: git config --global user.email "leehyeokjae97@gmail.com" && git config --global user.name "HyeokjaeLee"

      - name: Pull release branch
        run: git pull

      - uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8.3
          run_install: false

      - name: Set new patch version
        run: "pnpm version patch -m 'ver: to %s' && pnpm run patch"

      - name: Set new minor version
        if: "contains(github.event.head_commit.message, '+minor')"
        run: "pnpm version minor -m 'ver: to %s' && pnpm run minor"

      - name: Set new major version
        if: "contains(github.event.head_commit.message, '+major')"
        run: "pnpm version major -m 'ver: to %s' && pnpm run major"

      - name: Commit version up
        run: "git add -A && git commit -m 'ver: update' && git push"

  create_release_tag:
    if: "contains(github.event.head_commit.message, 'ver: to')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract version
        run: echo "version=$(echo ${{github.event.head_commit.message}} | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')" >> $GITHUB_ENV

      - uses: actions/create-release@v1
        with:
          tag_name: ${{ env.version }}
          release_name: ${{ env.version }}
