name: Ver

on:
  push:
    branches: "dev/*"

env:
  NODE_VERSION: "18.13"

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'ver: ')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.3
          run_install: true

      - name: Test eslint
        run: pnpm test:eslint

      - name: Test prettier
        run: pnpm test:prettier

  update:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.3
          run_install: false

      - name: Regist author
        run: git config --global user.email "leehyeokjae97@gmail.com" && git config --global user.name "HyeokjaeLee"

      - name: Pull branch
        run: git pull

      - name: Set new patch version
        if: "!contains(github.event.head_commit.message, '+m')"
        run: "pnpm version patch && pnpm run patch"

      - name: Set new minor version
        if: "contains(github.event.head_commit.message, '+minor')"
        run: "pnpm version minor && pnpm run minor"

      - name: Set new major version
        if: "contains(github.event.head_commit.message, '+major')"
        run: "pnpm version major && pnpm run major"

      - name: Get version
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3
        with:
          path: .

      - name: Commit new version
        run: "git reset HEAD^ && git add -A && git commit -m 'ver: ${{ steps.get-version.outputs.version }}' && git push"

  tag:
    needs: update
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Pull branch
        run: git pull

      - name: Get version
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3
        with:
          path: .

      - name: Create release & tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-version.outputs.version }}
          release_name: ${{ steps.get-version.outputs.version }}
